# Lineare Algebra

Heute werden wir die essentiellen mathematische Grundlagen für Neuronale Netzwerke erklären.

Das erste mathematische Konzept notwenig ist der **Vektor**
Ein Vektor ist Sammlung von mehrer Werte, und wird wie folgt definiert

$$\begin{bmatrix}3 & 4 & 0.5\end{bmatrix}$$ 
Dieser Vektor enthält genau drei Werte. Mit Vektoren können wir einzelne Datenpunkt beschrieben. Zum Beispiel könnten wir die Daten eines Hauses in diesem Vektor speichern. Der erste Werte gibt an viele Bäder das Haus hatz, der zweite wie viele Schlafzimmer, und der dritte Wert gibt das Alter der Heizung in Jahren an.

Ihnen ist bestimmt aufgefallen, dass ein Vektor erstaunlich Ähnlichkeiten zum einem 1-dimensionalen `array` hat.
`array([3,4,0.5])`. Tatsächlich, sollen `np.arrays` die gleiche Funktionen wie Vektoren haben. Die mathematischen Regeln die für Vektoren gelten, gelten auch für die `arrays`.



Wir können zum Beispiel einen Vektor mit einer Zahl multiplizieren:
*Für bessere Übersicht schreiben wir den Vektor untereinander*
$$3\cdot\begin{bmatrix}3 \\ 4 \\ 0.5\end{bmatrix}= \begin{bmatrix}3\cdot 3 \\ 4 \cdot 3 \\ 0.5 \cdot 3\end{bmatrix}= \begin{bmatrix}9 \\ 12 \\ 1.5\end{bmatrix} $$ 

In [4]:
import numpy as np
np.array([3,4,0.5])*3

array([ 9. , 12. ,  1.5])

Gleiches gilt auch für Addition und Substraktion:
$$3+\begin{bmatrix}3 \\ 4 \\ 0.5\end{bmatrix}= \begin{bmatrix}3+3 \\ 4+3 \\ 0.5 + 3\end{bmatrix}= \begin{bmatrix}6 \\ 7 \\ 3.5\end{bmatrix} $$ 

In [10]:
3+np.array([3,4,0.5])

array([6. , 7. , 3.5])

Interessant werden Vektoren erst, wenn wir mehrere miteinander multiplizieren:

$$\begin{bmatrix}3 \\ 4 \\ 0.5\end{bmatrix} \cdot \begin{bmatrix}0.3 \\ -2 \\ 0\end{bmatrix} $$

Das wird das Skalarprodukt genannt uind wir wie folgt berechnet.
$$\begin{bmatrix}3 \\ 4 \\ 0.5\end{bmatrix} \cdot \begin{bmatrix}0.3 \\ -2 \\ 0\end{bmatrix} = \begin{bmatrix}3 \cdot 0.3 \\ 4 \cdot -2 \\ 0.5 \cdot 0\end{bmatrix} = \begin{bmatrix}0.89 \\ -8 \\ 0\end{bmatrix} $$


In [1]:
np.array([3,4,0.5])* np.array([0.3,-2,0])

NameError: name 'np' is not defined

Wie Ihnen vielleicht schon aufgefallen ist, ähneln diese Vektormultiplikationen einer linaren Regression:

In [4]:
x    = np.array([3,4,0.5])
beta = np.array([0.3,-2,0])
x*beta

array([ 0.9, -8. ,  0. ])

### Matrizenmultiplikation

In [12]:
3*0.3

0.8999999999999999

In [2]:
import numpy as np
X = np.array([[1,3,-5],
              [2,0,1]])

W = np.array([[4,-2,-1],
              [6,0,-2],
              [1,0,3],
              [0,0,-1],
              [1,2,-1]])
X

array([[ 1,  3, -5],
       [ 2,  0,  1]])

Die Multiplikation der beiden Matrizen funktioniert nicht. In der Error Nachricht können Sie sehen, dass die erste Matrix eine `(2,3)` Matrix ist: Also 2 Reihen und 3 Spalten hat. Die zweite Matrix ist eine `(5,3)` Matrix. <br>
**Um zwei Matrizen zu multiplizieren, müssen die Anzahl der Spalten der ersten Matrix mit der Anzahl der Reihen der zweiten Matrix übereinstimmen.** <br>
Sie können `.transpose()` am Ende des Arrays benutzen um das Transpose von `W` zu bekommen, dabei werden Reihen und Spalten vertauscht, beziehungsweise an der Diagonalen gespiegelt:

In [ ]:
X*W.transpose()

**Funktioniert immer noch nicht ob wohl jetzt die Spalten und Reihen übereinstimmen.**

Das Problem ist das `*` in Numpy nicht für Matrixmultiplikation benutzt werden kann. `*` wird benutzt um das Hadamard-Produkt/komponentenweises Produkt zweier Matrizen auszurechnen, bei dem beide Matrizen gleich groß sein müssen.<br>
<center><img src="https://3.bp.blogspot.com/-CL15QzGDtMQ/WywZSeYQJ-I/AAAAAAAASug/EmriaQF57yIBJ9STd7FAnep-fxgKjhl1QCLcBGAs/s640/Hadamard_0.png" style="width: 800px;"></center>
<h8><center>Fig. 5: HodentekHelp.com </center></h8>


Um eine klassische Matrixmultiplikation zu benutzen wir `np.matmul(X,W.transpose())`.  

In [ ]:
np.matmul(X,W.transpose())

So funktionert endlich die Matrixmultiplikation mit Numpy:

Sie können auch einen Vektor `b` erstellen, den wir nach der Multiplikation addieren. Hierbei müssen Sie auf nichts besonderes achten. Damit haben Sie schon die lineare Transformation in einem Neuronalen Netzwerk. 

In [ ]:
b = np.array([1,2,0,3,-1])
np.matmul(X,W.transpose()) + b